spring:
  application:
    name: TOOLBOX-API

swagger:
  title: Toolbox API
  version: 1.0.0
  contact:
    name: THRAEX
    email: THRAEX@aliyun.com
  exclude-path: /error

thraex:
  date-time-format:
    date: yyyy-MM-dd
    time: HH:mm:ss
    date-time: ${thraex.date-time-format.date} ${thraex.date-time-format.time}
